create table if not exists public.holiday_packages (
  id bigint generated by default as identity primary key,
  title text not null,
  destination text not null,
  description text,
  duration text,
  starting_price numeric(12,2),
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.holiday_packages enable row level security;

drop policy if exists "Public can read active packages" on public.holiday_packages;

create policy "Public can read active packages"
on public.holiday_packages
for select
to anon, authenticated
using (active = true);

insert into public.holiday_packages
(title, destination, description, duration, starting_price, image_url)
values
('Dubai Escape', 'Dubai, UAE', 'City break with flexible sightseeing and hotel options.', '4N / 5D', 39999, 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80'),
('Singapore Getaway', 'Singapore', 'A compact Singapore holiday with hotel and sightseeing options.', '3N / 4D', 45999, 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80'),
('Thailand Highlights', 'Bangkok + Phuket', 'Beach and city combination package with flexible options.', '5N / 6D', 42999, 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80');


create table if not exists public.travel_enquiries (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  trip_type text not null check (trip_type in ('Round trip','One way')),
  from_airport text not null,
  to_airport text not null,
  departure_date date,
  return_date date,
  adults integer not null default 1 check (adults >= 1 and adults <= 20),
  children integer not null default 0 check (children >= 0 and children <= 20),
  cabin text not null default 'Economy',
  status text not null default 'new' check (status in ('new','contacted','quoted','booked','closed')),
  notification_status text not null default 'pending' check (notification_status in ('pending','sent','failed','not_configured')),
  created_at timestamptz not null default now()
);

alter table public.travel_enquiries enable row level security;

-- Customers do not receive permission to read enquiry records.
-- Submissions are handled by the submit-enquiry Edge Function using a server-side secret key.

create index if not exists travel_enquiries_created_at_idx on public.travel_enquiries(created_at desc);
create index if not exists travel_enquiries_status_idx on public.travel_enquiries(status);

-- Current four-enquiry-type migration is kept separately in migration-four-enquiry-types.sql.
-- Run that migration after this baseline schema when upgrading an existing project.
alter table public.holiday_packages add column if not exists gallery_images text[] not null default '{}';
