create table if not exists public.holiday_packages (
  id bigint generated by default as identity primary key,
  title text not null,
  destination text not null,
  description text,
  duration text,
  starting_price numeric(12,2),
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.holiday_packages enable row level security;

drop policy if exists "Public can read active packages" on public.holiday_packages;

create policy "Public can read active packages"
on public.holiday_packages
for select
to anon, authenticated
using (active = true);

insert into public.holiday_packages
(title, destination, description, duration, starting_price, image_url)
values
('Dubai Escape', 'Dubai, UAE', 'City break with flexible sightseeing and hotel options.', '4N / 5D', 39999, 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80'),
('Singapore Getaway', 'Singapore', 'A compact Singapore holiday with hotel and sightseeing options.', '3N / 4D', 45999, 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80'),
('Thailand Highlights', 'Bangkok + Phuket', 'Beach and city combination package with flexible options.', '5N / 6D', 42999, 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1200&q=80');
